### ISSUE TITLE
memory leak ?

### ISSUE THREAD

**Issue by kascote** [netdur/llama_cpp_dart#1]
When create an pointer to an utf8 from an string, you are allocating memory, but not releasing it after use, for example 

https://github.com/netdur/llama_cpp_dart/blob/main/lib/llm.dart#L25

here is an usage example from the FFI tests 

https://github.com/dart-lang/ffi/blob/main/test/utf8_test.dart#L21-L26

**Comment by netdur** [comment]
Yes, thank you for catching it, I will fix it.
