### ISSUE TITLE
Failed to lookup symbol 'llama_backend_init': None of the loaded modules contained the requested 

### ISSUE THREAD

**Issue by yagnikkorat** [netdur/llama_cpp_dart#22]
Unhandled exception:
Invalid argument(s): Failed to lookup symbol 'llama_backend_init': None of the loaded modules contained the requested symbol 'llama_backend_init'.
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
#1      llama_cpp._llama_backend_initPtr (package:llama_cpp_dart/src/llama_cpp.dart:10187:63)
#2      llama_cpp._llama_backend_initPtr (package:llama_cpp_dart/src/llama_cpp.dart)
#3      llama_cpp._llama_backend_init (package:llama_cpp_dart/src/llama_cpp.dart:10190:7)
#4      llama_cpp._llama_backend_init (package:llama_cpp_dart/src/llama_cpp.dart)
#5      llama_cpp.llama_backend_init (package:llama_cpp_dart/src/llama_cpp.dart:10181:12)
#6      new Llama (package:llama_cpp_dart/src/llama.dart:74:9)
#7      main (package:llm/main.dart:208:17)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

**Comment by netdur** [comment]
thanks for bug report I have resolved it
