### ISSUE TITLE
Documentation for Android 

### ISSUE THREAD

**Issue by king1484** [netdur/llama_cpp_dart#24]
Hello @netdur @danemadsen can you please provide an informative documentation for Android like how to compile the llama.cpp library.
I've read it on llama.cpp repo and compiled using cmake, but don't exactly know to get required files and keep them in the root folder of app. It's better if you guys give steps to get that file and where exactly to place. Thanks.

**Comment by netdur** [comment]
@danemadsen already wrote a documentation on using it here https://github.com/netdur/llama_cpp_dart/blob/main/doc/flutter.md see if that helps

**Comment by filippefrulli** [comment]
Hi there, I think what @king1484 refers to and what I also struggled with at first is how to get the libllama.dylib  (how to compile) and where to place it in the phone once we have it. I think I figured it out from the example application but that is only for windows. Having a cleared documentation would for sure help. If I can get it to work in the next few days I can send a PR with proposed changes to the readme.

**Comment by netdur** [comment]
@filippefrulli you can check here how I build llama.cpp for macos and ios https://github.com/netdur/llama_common_c/blob/main/run_build.sh
unfortunately I am not sure how to build it for android and window, you can check @danemadsen repo maid for android builds
