### ISSUE TITLE
No Podspec file found error

### ISSUE THREAD

**Issue by hgvur9gfh893o** [netdur/llama_cpp_dart#28]
I'm using llama_cpp_dart on macos, but after upgrading to 0.0.7, I get an error saying "No podspec found for `llama_cpp_dart` in `Flutter/ephemeral/.symlinks/plugins/llama_cpp_dart/macos". Is there a fix to this?

**Comment by whygee-dev** [comment]
@hgvur9gfh893o Facing the same error, how did you end up fixing it ?

**Comment by OfficialDarkComet** [comment]
This fixed it for me.
1) Go to the folder path: macos/Flutter/.symlinks/plugins/llama_cpp_dart/...
2) Create a folder called "macos"
3) Create a file called "llama_cpp_dart.podspec"
4) Paste this inside:
````podspec
Pod::Spec.new do |s|
    s.name             = 'llama_cpp_dart'
    s.version          = 'pre-alpha-exp'
    s.summary          = 'Llama Cpp Dart'
    s.homepage         = 'https://github.com/netdur/llama_cpp_dart'
    s.license          = { :type => 'MIT' }
    s.author           = { 'netdur' => 'team@myteam.com' }
    s.source           = { :git => '', :version => s.version.to_s }
    s.ios.deployment_target = '17.2'
    s.macos.deployment_target = '10.15'
    # Framework linking is handled by Flutter tooling, not CocoaPods.
    # Add a placeholder to satisfy `s.dependency 'Flutter'` plugin podspecs.
    s.vendored_frameworks = 'path/to/nothing'
  end
````

Everything else seems to work when running for MacOS, but it checks for a podspec file and so I gave it a dummy file.
Hope this helps!

~ Logan (DarkComet)
