### ISSUE TITLE
libllama.so doesnt seem to be loading correctly

### ISSUE THREAD

**Issue by danemadsen** [netdur/llama_cpp_dart#3]
It seems libllama.so isn't being loaded into llama_cpp_dart as flutter is looking for ```llama_backend_init```  in ```libflutter_linux_gtk.so```.

You can view my implementation here:
https://github.com/danemadsen/maid

The LlamaProcessor logic is in static/local_generation.dart and Llama.libraryPath is set as part of the main function in main.dart

I'm currently in the process of moving from my own implementation of llama.cpp for dart to yours so i would appreciate any help.

In my old implementation i was loading dynamic libraries in a very similar way to you so i cant see why it isn't working.

```
(maid:18359): Gdk-CRITICAL **: 21:44:41.856: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_modelSendPort@713439413' has not been initialized.
#0      LlamaProcessor.prompt (package:llama_cpp_dart/src/llama_processor.dart)
#1      LocalGeneration.prompt (package:maid/static/local_generation.dart:38)
#2      GenerationManager.prompt (package:maid/static/generation_manager.dart:20)
#3      Session.edit (package:maid/providers/session.dart:159)
#4      ChatMessageState.build.<anonymous closure>.<anonymous closure> (package:maid/widgets/chat_widgets/chat_message.dart:188)
#5      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309)
#9      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:279)
#10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167)
#11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:492)
#12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468)
#13     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:439)
#14     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413)
#15     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376)
#16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323)
#17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292)
#18     _invoke1 (dart:ui/hooks.dart:328)
#19     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:410)
#20     _dispatchPointerDataPacket (dart:ui/hooks.dart:262)

[ERROR:flutter/runtime/dart_isolate.cc(1097)] Unhandled exception:
Invalid argument(s): Failed to lookup symbol 'llama_backend_init': /home/danemadsen/maid/build/linux/x64/release/bundle/lib/libflutter_linux_gtk.so: undefined symbol: llama_backend_init
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33)
#1      llama_cpp._llama_backend_initPtr (package:llama_cpp_dart/src/llama_cpp.dart:10187)
#2      llama_cpp._llama_backend_init (package:llama_cpp_dart/src/llama_cpp.dart)
#3      llama_cpp.llama_backend_init (package:llama_cpp_dart/src/llama_cpp.dart)
#4      new Llama (package:llama_cpp_dart/src/llama.dart:65)
#5      LlamaProcessor._modelIsolateEntryPoint.<anonymous closure> (package:llama_cpp_dart/src/llama_processor.dart:89)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#9      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784)
#10     _StreamController._add (dart:async/stream_controller.dart:658)
#11     _StreamController.add (dart:async/stream_controller.dart:606)
#12     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
```

**Comment by netdur** [comment]
Hey @danemadsen, your app is fantastic! Thanks for creating it.

Regarding your query, it looks like you're using Linux. Could you try specifying the full path for `libllama.so` in `Llama.libraryPath`?

Also, about your previous comment, I'd appreciate some guidance on integrating it directly. I'll handle the iOS/macOS part.

**Comment by danemadsen** [comment]
@netdur
Much obliged, your work on this package is really going to help if I can get it to work.

I've tried a few different paths to attempt to load  the .so

In theory it should just be 'libllama.so', as in my old implementation the path I was using was 'libcore.so' (which lives in the same directory as libllama.so). You can view this logic in the models/LibraryLink.dart file in the main repo of maid
https://github.com/Mobile-Artificial-Intelligence/maid

However I've also tried ./lib/libllama.so, ./libllama.so. I havnt tried it on other platforms yet but I assume it will be a similar error.

I have a hunch that the reason its not working isn't because the path is incorrect (because it worked in the old implementation), but because I think the program is attempting to load the dynamic library before libraryPath is set, leading to DynamicLibrary.process() being used instead which is why its looking for the function in libflutter_gtk.so

**Comment by netdur** [comment]
I apologize for any confusion. Yes, libraryPath needs to be set before constructing the object. Here's an example:

```dart
import 'dart:io';

import 'package:llama_cpp_dart/llama_cpp_dart.dart';
import 'package:system_info2/system_info2.dart';

void main() async {
  final cores = SysInfo.cores;
  int memory = SysInfo.getTotalVirtualMemory() ~/ megaByte;

  Llama.libraryPath = "/Users/adel/Workspace/llama.cpp/build/libllama.dylib";

  ModelParams modelParams = ModelParams();

  ContextParams contextParams = ContextParams();
  contextParams.threads = cores.length;
  contextParams.threadsBatch = cores.length;

  Llama llama = Llama(
      "/Users/adel/Workspace/llama.cpp/models/mistral-7b-openorca.Q5_K_M.gguf",
      modelParams,
      contextParams);

  String system =
      "You are MistralOrca, a large language model trained by Alignment Lab AI. Write out your reasoning step-by-step to be sure you get the right answers!";
  String prompt = "How are you?";
  String input = """<|im_start|>system\n
$system<|im_end|>\n
<|im_start|>user\n
$prompt<|im_end|>\n
<|im_start|>assistant\n
""";

  llama.setPrompt(input);
  while (true) {
    var (token, done) = llama.getNext();
    stdout.write(token);
    if (done) break;
  }
  stdout.write("\n");

  llama.dispose();
}

const int megaByte = 1024 * 1024;
```

**Comment by danemadsen** [comment]
Yeah that's how i thought it must work. The issue is, from what i understand the ```Llama``` object is handled by the ```LlamaProcessor``` object when using flutter.So is there a way to set the LibraryPath for the ```LlamaProcessor``` or should i switch to directly using a ```Llama``` object for the flutter implementation.

this is how I'm currently attempting to do it

```
import 'package:llama_cpp_dart/llama_cpp_dart.dart';
import 'package:maid/models/generation_options.dart';
import 'package:maid/static/logger.dart';

class LocalGeneration {
  static LlamaProcessor? llamaProcessor;

  static void prompt(
    String input,
    GenerationOptions options,
    void Function(String?) callback
  ) async {
    if (llamaProcessor == null) {
      ModelParams modelParams = ModelParams();
      ContextParams contextParams = ContextParams();
      contextParams.batch = 512;
      contextParams.context = 512;

      if (Platform.isWindows) {
            Llama.libraryPath = 'llama.dll';
      } else if (Platform.isLinux || Platform.isAndroid) {
            Llama.libraryPath = 'libllama.so';
      }
      
      llamaProcessor = LlamaProcessor(
        options.path!, 
        modelParams, 
        contextParams
      );
    }

    llamaProcessor!.stream.listen((data) {
      callback.call(data);
    });

    llamaProcessor?.prompt(input);
  }

  static void stop() {
    llamaProcessor?.stop();
  }

  static void dispose() {
    llamaProcessor?.unloadModel();
    llamaProcessor = null;
  }
}
```

As you can see the ```Llama.libraryPath``` is being set before the ```LlamaProcessor``` is created. If you could provide a working example for flutter that would be very helpful.

**Comment by danemadsen** [comment]
Ok, from looking at your code it seems the problem likely is that ```Llama.lib``` is being accessed from within an isolate which causes ```libraryPath``` to be null as memory is not shared between isolates.

**Comment by BrutalCoding** [comment]
> @netdur Much obliged, your work on this package is really going to help if I can get it to work.
> 
> I've tried a few different paths to attempt to load the .so
> 
> In theory it should just be `libllama.so`, as in my old implementation the path I was using was `libcore.so` (which lives in the same directory as `libllama.so`). You can view this logic in the `lib/models/library_link.dart` file in the main repo of maid https://github.com/Mobile-Artificial-Intelligence/maid
> 
> However I've also tried `./lib/libllama.so`, `./libllama.so`. I havnt tried it on other platforms yet but I assume it will be a similar error.
> 
> I have a hunch that the reason its not working isn't because the path is incorrect (because it worked in the old implementation), but because I think the program is attempting to load the dynamic library before libraryPath is set, leading to `DynamicLibrary.process()` being used instead which is why its looking for the function in `libflutter_linux_gtk.so`

Heya, funny that I find you here. Someone told me about your project (Maid) in a Flutter library I published last month: https://github.com/BrutalCoding/aub.ai/issues/9. I told him 

It's a Flutter library that relies on llama.cpp too, similar to this repo. Although aub_ai will incorparate more local libraries (e.g. tts, stt, image gen). I've published video's on YT showing the included example app running on physical devices such as on my [Pixel 7](https://www.youtube.com/watch?v=SBaSpwXRz94), [2 PC's running Ubuntu](https://www.youtube.com/watch?v=LOTCvGnO7lg) and the other platforms such as iOS & Mac ([TestFlight here](https://testflight.apple.com/join/XuTpIgyY)).



> Ok, from looking at your code it seems the problem likely is that `Llama.lib` is being accessed from within an isolate which causes `libraryPath` to be null as memory is not shared between isolates.

I remember having similar issues with isolates. If I recall this correctly, I don't load the library (.so/.dll/dylib etc) in a seperate isolate since it's not compute heavy anyways. The part where llama.cpp is running inference on a LLM model should stay in a separate isolate of course, as I see that this repo is doing already (so does aub_ai).

**Comment by danemadsen** [comment]
> > @netdur Much obliged, your work on this package is really going to help if I can get it to work.
> > I've tried a few different paths to attempt to load the .so
> > In theory it should just be `libllama.so`, as in my old implementation the path I was using was `libcore.so` (which lives in the same directory as `libllama.so`). You can view this logic in the `lib/models/library_link.dart` file in the main repo of maid https://github.com/Mobile-Artificial-Intelligence/maid
> > However I've also tried `./lib/libllama.so`, `./libllama.so`. I havnt tried it on other platforms yet but I assume it will be a similar error.
> > I have a hunch that the reason its not working isn't because the path is incorrect (because it worked in the old implementation), but because I think the program is attempting to load the dynamic library before libraryPath is set, leading to `DynamicLibrary.process()` being used instead which is why its looking for the function in `libflutter_linux_gtk.so`
> 
> Heya, funny that I find you here. Someone told me about your project (Maid) in a Flutter library I published last month: [BrutalCoding/aub.ai#9](https://github.com/BrutalCoding/aub.ai/issues/9).
> 
> It's a Flutter library that relies on llama.cpp too, similar to this repo. Although aub_ai will incorporate more local libraries (e.g. tts, stt, image gen) over time. I've published video's on YT showing the included example app running on physical devices such as on my [Pixel 7](https://www.youtube.com/watch?v=SBaSpwXRz94), [2 PC's running Ubuntu](https://www.youtube.com/watch?v=LOTCvGnO7lg) and the other platforms such as iOS & Mac ([TestFlight here](https://testflight.apple.com/join/XuTpIgyY)).
> 
> > Ok, from looking at your code it seems the problem likely is that `Llama.lib` is being accessed from within an isolate which causes `libraryPath` to be null as memory is not shared between isolates.
> 
> I remember having similar issues with isolates. If I recall this correctly, I don't load the library (.so/.dll/dylib etc) in a seperate isolate since it's not compute heavy anyways. The part where llama.cpp is running inference on a LLM model should stay in a separate isolate of course, as I see that this repo is doing already (so does aub_ai).
> 
> --edit-- Oh shit, you're fast haha I noticed you submitted a PR with a fix. Keep in mind that iOS and MacOS is a bit more involved, especially if you want to keep sandbox on (required if distributing on App Store).

Oh wow, i remember checking out your repo when I first started development on maid. Its really come along way.

yes as you may be able to see in the maid repo discussions and issues my implementation of llama.cpp has broken itself 3 or 4 times majorly and its gotten to the point where i was about to drop support for it all together. I had a quick look at your project and yeah it looks like it might help me alot.

Always good to support another Aussie too.
