### ISSUE TITLE
CMake Error at CMakeLists.txt:16

### ISSUE THREAD

**Issue by filippefrulli** [netdur/llama_cpp_dart#30]
Hi there,

When I try to run the example Flutter App described in the Readme, I get following error:
CMake Error at CMakeLists.txt:16
add_subdirectory given source "./llama.cpp" which is not an existing directory.

From the CMaleLists.txt in the package at .pub-cache/hosted/pub.dev/llama_cpp_dart-0.0.7/src.

What am I doing wrong?
Many Thanks :)

**Comment by netdur** [comment]
Hello @filippefrulli this is weird, can you clone llama.cpp as submodule to folder llama.cpp and try again

**Comment by filippefrulli** [comment]
Hi, Should I clone it into the .pub-cache folder? Shouldn't that come from the package?

What I've done so far is:
Create a new Flutter Project.
Replaced the main.dart with the Flutter Application code in the Readme.
Run flutter pub get to get the packages

Then flutter run fails with above error. I have the compiled library and a gguf model ready but I guess that's not the issue here

**Comment by filippefrulli** [comment]
Fixed thank you
