### ISSUE TITLE
Building for Android

### ISSUE THREAD

**Issue by torphix** [netdur/llama_cpp_dart#7]
Hi! Thanks for the great lib.

With respect to building for android im building using:
$ mkdir build-android
$ cd build-android
$ export NDK=<your_ndk_directory>
$ cmake -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-23 -DCMAKE_C_FLAGS=-march=armv8.4a+dotprod ..
$ make

And the libllama.so file is successfully loading, however the model file isn't loading from the assets/models/<model_name>.gguf file
I've tested with linux build and the model successfully loads

Do you know if its a problem with how I am building the .so file for android or is it perhaps the location of my model needs to be different on android?

I'd appreciate any pointers in the right direction

**Comment by netdur** [comment]
Yes, you should extract model from assets to local directory, then load it from there
https://github.com/netdur/llama_cpp_dart/blob/main/example/main.dart#L55

**Comment by torphix** [comment]
Okay thank you,
how are you loading the initial model? as there seems to be a cap on the filesize, im getting the error: 
```
 Dart Error: NewExternalTypedData expects argument 'length' to be in the range [0..1073741823].
```
Are you downloading the model from a remote host then transferring?
