### ISSUE TITLE
Use gpt_params instead of model_params and context_params

### ISSUE THREAD

**Issue by danemadsen** [netdur/llama_cpp_dart#9]
This would expose many more params to the user and would simplify the process. The issue is i cant seem to get the bindings to generate on my system. You will need to include llama.cpp/common/common.h to use gpt_params

**Comment by netdur** [comment]
Yes, there are two issues:

'common.h' is internal code and should not be used as an API.
'common.h' depends on 'sampling.h', which contains C++ code in its header. Dart/FFI can't handle this, which is why you're unable to generate its binding.
I've actually created a C wrapper for it here: https://github.com/netdur/llama_common_c

Yesterday, I started new code to implement sampling in pure Dart, effectively converting all those parameters you need

**Comment by danemadsen** [comment]
> Yes, there are two issues:
> 
> 'common.h' is internal code and should not be used as an API. 'common.h' depends on 'sampling.h', which contains C++ code in its header. Dart/FFI can't handle this, which is why you're unable to generate its binding. I've actually created a C wrapper for it here: https://github.com/netdur/llama_common_c
> 
> Yesterday, I started new code to implement sampling in pure Dart, effectively converting all those parameters you need

That would be awesome if you could get that working. Yeah i gave it shot also but found everything but c++ strings works

**Comment by netdur** [comment]
@danemadsen I did initial work to implement SamplingParams and implemented repetition penalties
https://github.com/netdur/llama_cpp_dart/blob/main/lib/src/llama.dart#L204

After a quick review of other bindings, it seems that, aside from Python, all are utilizing gpt_params in their implementation. Considering this, it might be wise for me to adopt the same approach. However, this would involve compiling some C code and integrating my efforts with llama_common_c

**Comment by danemadsen** [comment]
> @danemadsen I did initial work to implement SamplingParams and implemented repetition penalties
> https://github.com/netdur/llama_cpp_dart/blob/main/lib/src/llama.dart#L204
> 
> After a quick review of other bindings, it seems that, aside from Python, all are utilizing gpt_params in their implementation. Considering this, it might be wise for me to adopt the same approach. However, this would involve compiling some C code and integrating my efforts with llama_common_c

If you're going to do that its basically going to make it so a custom version of llama.CPP is needed for the bindings (which is fine) but the way we are currently doing it is to bind the the library in llama_CPP_dart and then link it to the actual .so elsewhere (eg in maid)

**Comment by netdur** [comment]
@danemadsen I have ported all code in sampling.cpp to dart https://github.com/netdur/llama_cpp_dart/blob/main/lib/src/sampling_context.dart
this covers a lot of options, but not all of them, if you don't mind, which options should I focus on?

**Comment by danemadsen** [comment]
> @danemadsen I have ported all code in sampling.cpp to dart https://github.com/netdur/llama_cpp_dart/blob/main/lib/src/sampling_context.dart
> this covers a lot of options, but not all of them, if you don't mind, which options should I focus on?

I don't actually know as I rarely ever tweak them much myself but a few of my users have expressed need for min_p and top_k in the past

**Comment by Solido** [comment]
Hi, I'm following your work with interest. Here are the most used one ordered to control a model.

https://github.com/ggerganov/llama.cpp/pull/4882#issuecomment-1907570980

**Comment by netdur** [comment]
@danemadsen here I have covered those options [here](https://github.com/netdur/llama_cpp_dart/blob/main/lib/src/sampling_context.dart#L52) I will work integrate them on Llama

thank you @Solido I actually have your list as my [task list]( https://github.com/netdur/llama_cpp_dart/blob/SequenceFilter/lib/src/llama.dart#L11) I just have no idea what all those options do, I can't really test if they are working as intended.

for your edit: it really depends on your context size, this crash would happen if prompt is exceed context size, to avoid crash I need to implement `keep` related functions where prompt recycle previous tokens... 

also you may need to call clear between prompts to avoid mixing it response.

**Comment by netdur** [comment]
good news https://github.com/ggerganov/llama.cpp/issues/5214

**Comment by danemadsen** [comment]
> good news [ggerganov/llama.cpp#5214](https://github.com/ggerganov/llama.cpp/issues/5214)

Thats going to be helpful

**Comment by netdur** [comment]
list of implemented / unimplemented parameters   https://github.com/netdur/llama_cpp_dart/commit/c51f7d8b0aa3bbdaa124e58823a3577bab143696

**Comment by Solido** [comment]
This is great! I'm just out of luck right now because I can't load any models.
I'm building often so surely my llama dylib is out of sync and too recent.
I'll wait for your next release/sync.
